export const USER_CREATE_TRANSACTION_REQUEST = 'USER_CREATE_TRANSACTION_REQUEST';
export const USER_CREATE_TRANSACTION_SUCCESS = 'USER_CREATE_TRANSACTION_SUCCESS';
export const USER_CREATE_TRANSACTION_FAILURE = 'USER_CREATE_TRANSACTION_FAILURE';

export const USER_GET_TRANSACTION_REQUEST = 'USER_GET_TRANSACTION_REQUEST';
export const USER_GET_TRANSACTION_SUCCESS = 'USER_GET_TRANSACTION_SUCCESS';
export const USER_GET_TRANSACTION_FAILURE = 'USER_GET_TRANSACTION_FAILURE';

export const GET_QUOTES_REQUEST = 'GET_QUOTES_REQUEST';
export const GET_QUOTES_SUCCESS = 'GET_QUOTES_SUCCESS';
export const GET_QUOTES_FAILURE = 'GET_QUOTES_FAILURE';
