export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
