export const USER_ACCOUNT_REQUEST = 'USER_ACCOUNT_REQUEST';
export const USER_ACCOUNT_SUCCESS = 'USER_ACCOUNT_SUCCESS';
export const USER_ACCOUNT_FAILURE = 'USER_ACCOUNT_FAILURE';

export const CREATE_USER_ACCOUNT_REQUEST = 'CREATE_USER_ACCOUNT_REQUEST';
export const CREATE_USER_ACCOUNT_SUCCESS = 'CREATE_USER_ACCOUNT_SUCCESS';
export const CREATE_USER_ACCOUNT_FAILURE = 'CREATE_USER_ACCOUNT_FAILURE';
